#include "reports.h"
#include "utils.h"
#include "input_validation.h"
#include "ui_components.h"

// ============================================
// HELPER: REPORT HEADER GENERATOR
// ============================================
void printReportHeader(const string& reportTitle, const string& startDate, const string& endDate) {
    cout << "\n\033[36m" << u8"╔════════════════════════════════════════════════════════════════════════════════╗" << "\033[0m" << endl;
    cout << "\033[36m" << u8"║" << "\033[0m";

    // Center the title
    int totalWidth = 80;
    int titleLen = reportTitle.length();
    int padding = (totalWidth - titleLen) / 2;
    for (int i = 0; i < padding; i++) cout << " ";
    cout << "\033[1;97m" << reportTitle << "\033[0m";
    for (int i = 0; i < (totalWidth - titleLen - padding); i++) cout << " ";
    cout << "\033[36m" << u8"║" << "\033[0m" << endl;

    cout << "\033[36m" << u8"╠════════════════════════════════════════════════════════════════════════════════╣" << "\033[0m" << endl;

    // Company Info
    cout << "\033[36m" << u8"║" << "\033[0m  \033[1;97mCAR SERVICE CENTER ORGANISER\033[0m                                                  \033[36m" << u8"║" << "\033[0m" << endl;

    // Date Range
    string dateRange = "Period: " + startDate + " to " + endDate;
    cout << "\033[36m" << u8"║" << "\033[0m  " << left << setw(78) << dateRange << "\033[36m" << u8"║" << "\033[0m" << endl;

    // Generated By
    string generatedBy = "Generated By: " + currentStaffName + " (" + currentUserRole + ")";
    cout << "\033[36m" << u8"║" << "\033[0m  " << left << setw(78) << generatedBy << "\033[36m" << u8"║" << "\033[0m" << endl;

    // Generated At
    time_t now = time(0);
    struct tm tstruct;
    char buf[80];
    localtime_s(&tstruct, &now);
    strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", &tstruct);
    string generatedAt = "Generated At: " + string(buf);
    cout << "\033[36m" << u8"║" << "\033[0m  " << left << setw(78) << generatedAt << "\033[36m" << u8"║" << "\033[0m" << endl;

    cout << "\033[36m" << u8"╚════════════════════════════════════════════════════════════════════════════════╝" << "\033[0m" << endl;
}

void printReportFooter(int totalRecords) {
    cout << "\n\033[36m" << u8"════════════════════════════════════════════════════════════════════════════════" << "\033[0m" << endl;
    cout << "\033[90m[End of Report | Total Records: " << totalRecords << "]\033[0m" << endl;
}

void printSectionDivider(const string& sectionTitle) {
    int totalWidth = 80;
    int titleLen = (int)sectionTitle.length();
    int innerWidth = totalWidth - 2; // -2 for corners ┌ ┐
    int availableForDashes = innerWidth - titleLen - 2; // -2 for spaces around title
    int leftDashes = availableForDashes / 2;
    int rightDashes = availableForDashes - leftDashes;

    cout << "\n\033[36m" << u8"┌"
         << repeatString(u8"─", leftDashes)
         << " \033[1;97m" << sectionTitle << "\033[0;36m "
         << repeatString(u8"─", rightDashes)
         << u8"┐" << "\033[0m" << endl;
}

// ============================================
// ACCESS CONTROL CHECK
// ============================================
bool checkReportAccess() {
    if (currentUserRole != "Manager") {
        cout << "\n\033[31m" << u8"╔════════════════════════════════════════════════════════════╗" << "\033[0m" << endl;
        cout << "\033[31m" << u8"║" << "         ACCESS DENIED - MANAGER ONLY                       " << u8"║" << "\033[0m" << endl;
        cout << "\033[31m" << u8"║" << "  Analytics & Reports require Manager-level access.         " << u8"║" << "\033[0m" << endl;
        cout << "\033[31m" << u8"║" << "  Please contact your Manager for report requests.          " << u8"║" << "\033[0m" << endl;
        cout << "\033[31m" << u8"╚════════════════════════════════════════════════════════════╝" << "\033[0m" << endl;
        pause();
        return false;
    }
    return true;
}

// ============================================
// 1. APPOINTMENT SCHEDULE REPORT (DETAILED)
// ============================================
void viewAppointmentSchedule() {
    clearScreen();
    printSectionTitle("APPOINTMENT SCHEDULE REPORT");

    try {
        printSubHeader("Define Report Period");
        string startDate = getSmartDateInput("Enter Start Date (YYYYMMDD)");
        string endDate = getSmartDateInput("Enter End Date (YYYYMMDD)  ");

        if (startDate > endDate) {
            showWarning("Invalid Range: Start Date cannot be after End Date.");
            pause();
            return;
        }

        // Main Query - Get all appointments with full details
        showLoadingStart("Generating report");
        string query = "SELECT a.appointmentId, st.slotDate, st.slotTime, a.endTime, "
            "c.customerName, c.phoneNumber, v.licensePlate, v.brand, v.model, "
            "sb.bayName, a.status, a.notes, a.createdDate "
            "FROM APPOINTMENT a "
            "JOIN VEHICLE v ON a.vehicleId = v.vehicleId "
            "JOIN CUSTOMER c ON v.customerId = c.customerId "
            "JOIN SERVICE_BAY sb ON a.serviceBayId = sb.serviceBayId "
            "JOIN SLOT_TIME st ON a.slotTimeId = st.slotTimeId "
            "WHERE st.slotDate BETWEEN '" + startDate + "' AND '" + endDate + "' "
            "ORDER BY st.slotDate ASC, st.slotTime ASC";

        if (mysql_query(conn, query.c_str())) {
            showLoadingComplete();
            showError("Database Error: " + string(mysql_error(conn)));
            pause();
            return;
        }

        MYSQL_RES* result = mysql_store_result(conn);
        int totalAppointments = mysql_num_rows(result);
        showLoadingComplete();

        if (totalAppointments == 0) {
            showError("No appointments found for the selected period.");
            mysql_free_result(result);
            pause();
            return;
        }

        // Print Report Header
        printReportHeader("APPOINTMENT SCHEDULE REPORT", startDate, endDate);

        MYSQL_ROW row;
        string currentDate = "";
        int dailyCount = 0;
        int totalScheduled = 0, totalInProgress = 0, totalCompleted = 0, totalCancelled = 0;

        while ((row = mysql_fetch_row(result))) {
            string rowDate = row[1];

            // New Date Section
            if (rowDate != currentDate) {
                if (!currentDate.empty()) {
                    cout << "\033[90m   [" << dailyCount << " appointment(s) for " << currentDate << "]\033[0m\n" << endl;
                }

                printSectionDivider(rowDate);
                cout << "\033[36m" << left
                    << setw(6) << "ID"
                    << setw(10) << "Time"
                    << setw(18) << "Customer"
                    << setw(14) << "Phone"
                    << setw(12) << "Vehicle"
                    << setw(8) << "Bay"
                    << setw(12) << "Status"
                    << "\033[0m" << endl;
                cout << "\033[90m" << repeatString(u8"─", 80) << "\033[0m" << endl;

                currentDate = rowDate;
                dailyCount = 0;
            }

            // Status color coding
            string status = row[10];
            string statusColor;
            if (status == "Completed") { statusColor = "\033[32m"; totalCompleted++; }
            else if (status == "In Progress") { statusColor = "\033[33m"; totalInProgress++; }
            else if (status == "Cancelled") { statusColor = "\033[31m"; totalCancelled++; }
            else { statusColor = "\033[36m"; totalScheduled++; }

            // Print appointment row
            cout << left
                << setw(6) << row[0]                    // ID
                << setw(10) << row[2]                   // Time
                << setw(18) << string(row[4]).substr(0, 16)  // Customer Name
                << setw(14) << row[5]                   // Phone
                << setw(12) << row[6]                   // License Plate
                << setw(8) << row[9]                    // Bay
                << statusColor << setw(12) << status << "\033[0m"
                << endl;

            // Print vehicle details on next line
            cout << "\033[90m       " << u8"└─ Vehicle: " << row[7] << " " << row[8];
            if (row[11] && string(row[11]).length() > 0) {
                cout << " | Notes: " << row[11];
            }
            cout << "\033[0m" << endl;

            // Get services for this appointment
            string servQuery = "SELECT sv.serviceName, sv.basePrice, aps.serviceStatus, "
                "IFNULL(s.fullName, 'Unassigned') as mechanic "
                "FROM APPOINTMENT_SERVICE aps "
                "JOIN SERVICE_TYPE sv ON aps.serviceTypeId = sv.serviceTypeId "
                "LEFT JOIN STAFF s ON aps.staffId = s.staffId "
                "WHERE aps.appointmentId = " + string(row[0]);

            if (mysql_query(conn, servQuery.c_str()) == 0) {
                MYSQL_RES* servResult = mysql_store_result(conn);
                MYSQL_ROW servRow;
                while ((servRow = mysql_fetch_row(servResult))) {
                    cout << "\033[90m          " << u8"├─ " << servRow[0]
                        << " (RM " << servRow[1] << ") - "
                        << servRow[2] << " [" << servRow[3] << "]" << "\033[0m" << endl;
                }
                mysql_free_result(servResult);
            }

            dailyCount++;
        }

        // Final day count
        if (!currentDate.empty()) {
            cout << "\033[90m   [" << dailyCount << " appointment(s) for " << currentDate << "]\033[0m\n" << endl;
        }

        mysql_free_result(result);

        // Summary Section
        printSectionDivider("REPORT SUMMARY");
        cout << "\n\033[1;97m  Status Breakdown:\033[0m" << endl;
        cout << "  \033[36m" << u8"├─" << "\033[0m Scheduled:   " << totalScheduled << endl;
        cout << "  \033[33m" << u8"├─" << "\033[0m In Progress: " << totalInProgress << endl;
        cout << "  \033[32m" << u8"├─" << "\033[0m Completed:   " << totalCompleted << endl;
        cout << "  \033[31m" << u8"└─" << "\033[0m Cancelled:   " << totalCancelled << endl;
        cout << "\n  \033[1;97mTOTAL APPOINTMENTS: " << totalAppointments << "\033[0m" << endl;

        printReportFooter(totalAppointments);
    }
    catch (OperationCancelledException&) {}
    pause();
}

// ============================================
// 2. FINANCIAL REPORT (DETAILED SALES)
// ============================================
void viewFinancialReport() {
    clearScreen();
    printSectionTitle("FINANCIAL REPORT - SALES");

    try {
        printSubHeader("Define Report Period");
        string startDate = getSmartDateInput("Enter Start Date (YYYYMMDD)");
        string endDate = getSmartDateInput("Enter End Date (YYYYMMDD)  ");

        if (startDate > endDate) {
            showWarning("Invalid Range: Start Date cannot be after End Date.");
            pause();
            return;
        }

        showLoadingStart("Generating financial report");
        printReportHeader("FINANCIAL REPORT - SALES", startDate, endDate);

        // Section 1: Daily Revenue Breakdown
        printSectionDivider("DAILY REVENUE BREAKDOWN");

        string dailyQuery = "SELECT DATE(st.slotDate) as day, "
            "COUNT(DISTINCT a.appointmentId) as appointments, "
            "COUNT(aps.appointmentServiceId) as services_done, "
            "SUM(sv.basePrice) as revenue "
            "FROM APPOINTMENT_SERVICE aps "
            "JOIN APPOINTMENT a ON aps.appointmentId = a.appointmentId "
            "JOIN SLOT_TIME st ON a.slotTimeId = st.slotTimeId "
            "JOIN SERVICE_TYPE sv ON aps.serviceTypeId = sv.serviceTypeId "
            "WHERE aps.serviceStatus = 'Completed' "
            "AND st.slotDate BETWEEN '" + startDate + "' AND '" + endDate + "' "
            "GROUP BY day ORDER BY day";

        if (mysql_query(conn, dailyQuery.c_str())) {
            showLoadingComplete();
            showError("Error: " + string(mysql_error(conn)));
            pause();
            return;
        }

        MYSQL_RES* dailyResult = mysql_store_result(conn);
        showLoadingComplete();

        cout << "\033[36m" << left
            << setw(15) << "Date"
            << setw(15) << "Appointments"
            << setw(15) << "Services"
            << setw(18) << "Revenue (RM)"
            << "\033[0m" << endl;
        cout << "\033[90m" << repeatString(u8"─", 65) << "\033[0m" << endl;

        MYSQL_ROW row;
        double totalRevenue = 0;
        int totalAppointments = 0;
        int totalServices = 0;

        while ((row = mysql_fetch_row(dailyResult))) {
            double dayRevenue = atof(row[3]);
            cout << left
                << setw(15) << row[0]
                << setw(15) << row[1]
                << setw(15) << row[2]
                << "RM " << setw(15) << fixed << setprecision(2) << dayRevenue
                << endl;
            totalAppointments += atoi(row[1]);
            totalServices += atoi(row[2]);
            totalRevenue += dayRevenue;
        }
        mysql_free_result(dailyResult);

        cout << "\033[90m" << repeatString(u8"─", 65) << "\033[0m" << endl;
        cout << "\033[1;32m" << left << setw(15) << "TOTAL"
            << setw(15) << totalAppointments
            << setw(15) << totalServices
            << "RM " << fixed << setprecision(2) << totalRevenue
            << "\033[0m" << endl;

        // Section 2: Service Revenue Breakdown
        printSectionDivider("REVENUE BY SERVICE TYPE");

        string serviceQuery = "SELECT sv.serviceName, "
            "COUNT(aps.appointmentServiceId) as qty, "
            "sv.basePrice as unit_price, "
            "SUM(sv.basePrice) as total "
            "FROM APPOINTMENT_SERVICE aps "
            "JOIN APPOINTMENT a ON aps.appointmentId = a.appointmentId "
            "JOIN SLOT_TIME st ON a.slotTimeId = st.slotTimeId "
            "JOIN SERVICE_TYPE sv ON aps.serviceTypeId = sv.serviceTypeId "
            "WHERE aps.serviceStatus = 'Completed' "
            "AND st.slotDate BETWEEN '" + startDate + "' AND '" + endDate + "' "
            "GROUP BY sv.serviceTypeId ORDER BY total DESC";

        if (mysql_query(conn, serviceQuery.c_str()) == 0) {
            MYSQL_RES* serviceResult = mysql_store_result(conn);

            cout << "\033[36m" << left
                << setw(30) << "Service Name"
                << setw(10) << "Qty"
                << setw(15) << "Unit Price"
                << setw(15) << "Total (RM)"
                << "\033[0m" << endl;
            cout << "\033[90m" << repeatString(u8"─", 70) << "\033[0m" << endl;

            while ((row = mysql_fetch_row(serviceResult))) {
                cout << left
                    << setw(30) << row[0]
                    << setw(10) << row[1]
                    << "RM " << setw(12) << row[2]
                    << "RM " << setw(12) << row[3]
                    << endl;
            }
            mysql_free_result(serviceResult);
        }

        // Section 3: Transaction Details
        printSectionDivider("COMPLETED TRANSACTION DETAILS");

        string transQuery = "SELECT a.appointmentId, st.slotDate, c.customerName, "
            "v.licensePlate, GROUP_CONCAT(sv.serviceName SEPARATOR ', ') as services, "
            "SUM(sv.basePrice) as total "
            "FROM APPOINTMENT a "
            "JOIN APPOINTMENT_SERVICE aps ON a.appointmentId = aps.appointmentId "
            "JOIN SERVICE_TYPE sv ON aps.serviceTypeId = sv.serviceTypeId "
            "JOIN VEHICLE v ON a.vehicleId = v.vehicleId "
            "JOIN CUSTOMER c ON v.customerId = c.customerId "
            "JOIN SLOT_TIME st ON a.slotTimeId = st.slotTimeId "
            "WHERE aps.serviceStatus = 'Completed' "
            "AND st.slotDate BETWEEN '" + startDate + "' AND '" + endDate + "' "
            "GROUP BY a.appointmentId "
            "ORDER BY st.slotDate, a.appointmentId";

        if (mysql_query(conn, transQuery.c_str()) == 0) {
            MYSQL_RES* transResult = mysql_store_result(conn);
            int transCount = mysql_num_rows(transResult);

            cout << "\033[36m" << left
                << setw(6) << "ID"
                << setw(12) << "Date"
                << setw(18) << "Customer"
                << setw(12) << "Vehicle"
                << setw(30) << "Services"
                << setw(12) << "Amount"
                << "\033[0m" << endl;
            cout << "\033[90m" << repeatString(u8"─", 90) << "\033[0m" << endl;

            while ((row = mysql_fetch_row(transResult))) {
                string services = row[4];
                if (services.length() > 28) services = services.substr(0, 25) + "...";

                cout << left
                    << setw(6) << row[0]
                    << setw(12) << row[1]
                    << setw(18) << string(row[2]).substr(0, 16)
                    << setw(12) << row[3]
                    << setw(30) << services
                    << "RM " << row[5]
                    << endl;
            }
            mysql_free_result(transResult);

            // Summary
            printSectionDivider("FINANCIAL SUMMARY");
            cout << "\n\033[1;97m  Revenue Statistics:\033[0m" << endl;
            cout << "  \033[36m" << u8"├─" << "\033[0m Total Appointments:     " << totalAppointments << endl;
            cout << "  \033[36m" << u8"├─" << "\033[0m Total Services Done:    " << totalServices << endl;
            cout << "  \033[36m" << u8"├─" << "\033[0m Transactions:           " << transCount << endl;
            cout << "  \033[32m" << u8"└─" << "\033[1;32m GROSS REVENUE:          RM " << fixed << setprecision(2) << totalRevenue << "\033[0m" << endl;

            if (totalAppointments > 0) {
                double avgPerAppointment = totalRevenue / totalAppointments;
                cout << "\n  \033[90mAverage Revenue per Appointment: RM " << fixed << setprecision(2) << avgPerAppointment << "\033[0m" << endl;
            }

            printReportFooter(transCount);
        }
    }
    catch (OperationCancelledException&) {}
    pause();
}

// ============================================
// 3. MECHANIC PERFORMANCE REPORT (DETAILED)
// ============================================
void viewMechanicPerformance() {
    clearScreen();
    printSectionTitle("MECHANIC PERFORMANCE REPORT");

    try {
        printSubHeader("Define Report Period");
        string startDate = getSmartDateInput("Enter Start Date (YYYYMMDD)");
        string endDate = getSmartDateInput("Enter End Date (YYYYMMDD)  ");

        if (startDate > endDate) {
            showWarning("Invalid Range: Start Date cannot be after End Date.");
            pause();
            return;
        }

        showLoadingStart("Generating performance report");
        printReportHeader("MECHANIC PERFORMANCE REPORT", startDate, endDate);

        // Get all mechanics with their performance
        string mechQuery = "SELECT s.staffId, s.fullName, "
            "COUNT(aps.appointmentServiceId) as jobs, "
            "SUM(sv.standardDuration) as expected_time, "
            "SUM(IFNULL(aps.actualDuration, sv.standardDuration)) as actual_time, "
            "SUM(sv.basePrice) as revenue "
            "FROM STAFF s "
            "LEFT JOIN APPOINTMENT_SERVICE aps ON s.staffId = aps.staffId "
            "AND aps.serviceStatus = 'Completed' "
            "LEFT JOIN SERVICE_TYPE sv ON aps.serviceTypeId = sv.serviceTypeId "
            "LEFT JOIN APPOINTMENT a ON aps.appointmentId = a.appointmentId "
            "LEFT JOIN SLOT_TIME st ON a.slotTimeId = st.slotTimeId "
            "AND st.slotDate BETWEEN '" + startDate + "' AND '" + endDate + "' "
            "WHERE s.role = 'Mechanic' AND s.isActive = 1 "
            "GROUP BY s.staffId "
            "ORDER BY revenue DESC";

        if (mysql_query(conn, mechQuery.c_str())) {
            showLoadingComplete();
            showError("Error: " + string(mysql_error(conn)));
            pause();
            return;
        }

        MYSQL_RES* mechResult = mysql_store_result(conn);
        int totalMechanics = mysql_num_rows(mechResult);
        showLoadingComplete();

        // Performance Summary Table
        printSectionDivider("PERFORMANCE SUMMARY");
        cout << "\033[36m" << left
            << setw(20) << "Mechanic"
            << setw(10) << "Jobs"
            << setw(15) << "Exp. Time"
            << setw(15) << "Act. Time"
            << setw(12) << "Efficiency"
            << setw(15) << "Revenue"
            << "\033[0m" << endl;
        cout << "\033[90m" << repeatString(u8"─", 87) << "\033[0m" << endl;

        MYSQL_ROW row;
        double totalRevenue = 0;
        int totalJobs = 0;
        vector<pair<int, string>> mechanicIds; // Store for detailed breakdown

        while ((row = mysql_fetch_row(mechResult))) {
            int jobs = row[2] ? atoi(row[2]) : 0;
            double expectedTime = row[3] ? atof(row[3]) : 0;
            double actualTime = row[4] ? atof(row[4]) : 0;
            double revenue = row[5] ? atof(row[5]) : 0;

            // Calculate efficiency
            double efficiency = (expectedTime > 0 && actualTime > 0) ? (expectedTime / actualTime) * 100 : 0;
            string effColor;
            if (efficiency >= 100) effColor = "\033[32m";
            else if (efficiency >= 80) effColor = "\033[33m";
            else effColor = "\033[31m";

            cout << left
                << setw(20) << row[1]
                << setw(10) << jobs;

            if (jobs > 0) {
                cout << setw(15) << (to_string((int)expectedTime) + " min")
                    << setw(15) << (to_string((int)actualTime) + " min")
                    << effColor << setw(12) << (to_string((int)efficiency) + "%") << "\033[0m"
                    << "RM " << fixed << setprecision(2) << revenue;
            } else {
                cout << setw(15) << u8"─" << setw(15) << u8"─" << setw(12) << u8"─" << u8"─";
            }
            cout << endl;

            totalJobs += jobs;
            totalRevenue += revenue;
            if (jobs > 0) {
                mechanicIds.push_back({atoi(row[0]), string(row[1])});
            }
        }
        mysql_free_result(mechResult);

        cout << "\033[90m" << repeatString(u8"─", 87) << "\033[0m" << endl;
        cout << "\033[1;32m" << left << setw(20) << "TOTAL"
            << setw(10) << totalJobs
            << setw(15) << "" << setw(15) << "" << setw(12) << ""
            << "RM " << fixed << setprecision(2) << totalRevenue
            << "\033[0m" << endl;

        // Detailed Job Breakdown per Mechanic
        for (auto& mech : mechanicIds) {
            printSectionDivider("JOB DETAILS: " + mech.second);

            string jobQuery = "SELECT st.slotDate, sv.serviceName, sv.standardDuration, "
                "IFNULL(aps.actualDuration, sv.standardDuration) as actual, "
                "sv.basePrice, v.licensePlate, c.customerName "
                "FROM APPOINTMENT_SERVICE aps "
                "JOIN SERVICE_TYPE sv ON aps.serviceTypeId = sv.serviceTypeId "
                "JOIN APPOINTMENT a ON aps.appointmentId = a.appointmentId "
                "JOIN SLOT_TIME st ON a.slotTimeId = st.slotTimeId "
                "JOIN VEHICLE v ON a.vehicleId = v.vehicleId "
                "JOIN CUSTOMER c ON v.customerId = c.customerId "
                "WHERE aps.staffId = " + to_string(mech.first) + " "
                "AND aps.serviceStatus = 'Completed' "
                "AND st.slotDate BETWEEN '" + startDate + "' AND '" + endDate + "' "
                "ORDER BY st.slotDate";

            if (mysql_query(conn, jobQuery.c_str()) == 0) {
                MYSQL_RES* jobResult = mysql_store_result(conn);

                cout << "\033[36m" << left
                    << setw(12) << "Date"
                    << setw(25) << "Service"
                    << setw(10) << "Std(m)"
                    << setw(10) << "Act(m)"
                    << setw(10) << "Price"
                    << setw(12) << "Vehicle"
                    << "\033[0m" << endl;
                cout << "\033[90m" << repeatString(u8"─", 79) << "\033[0m" << endl;

                while ((row = mysql_fetch_row(jobResult))) {
                    cout << left
                        << setw(12) << row[0]
                        << setw(25) << string(row[1]).substr(0, 23)
                        << setw(10) << row[2]
                        << setw(10) << row[3]
                        << "RM " << setw(7) << row[4]
                        << setw(12) << row[5]
                        << endl;
                }
                mysql_free_result(jobResult);
            }
        }

        // Summary
        printSectionDivider("PERFORMANCE SUMMARY");
        cout << "\n\033[1;97m  Team Statistics:\033[0m" << endl;
        cout << "  \033[36m" << u8"├─" << "\033[0m Active Mechanics:       " << totalMechanics << endl;
        cout << "  \033[36m" << u8"├─" << "\033[0m Total Jobs Completed:   " << totalJobs << endl;
        cout << "  \033[32m" << u8"└─" << "\033[1;32m Total Revenue Generated: RM " << fixed << setprecision(2) << totalRevenue << "\033[0m" << endl;

        if (totalJobs > 0 && totalMechanics > 0) {
            cout << "\n  \033[90mAverage Jobs per Mechanic: " << fixed << setprecision(1) << (double)totalJobs / totalMechanics << "\033[0m" << endl;
        }

        printReportFooter(totalJobs);
    }
    catch (OperationCancelledException&) {}
    pause();
}

// ============================================
// 4. SERVICE TRENDS REPORT (DETAILED)
// ============================================
void viewServiceTrends() {
    clearScreen();
    printSectionTitle("SERVICE TRENDS & POPULARITY");

    try {
        printSubHeader("Define Report Period");
        string startDate = getSmartDateInput("Enter Start Date (YYYYMMDD)");
        string endDate = getSmartDateInput("Enter End Date (YYYYMMDD)  ");

        if (startDate > endDate) {
            showWarning("Invalid Range: Start Date cannot be after End Date.");
            pause();
            return;
        }

        showLoadingStart("Generating trends report");
        printReportHeader("SERVICE TRENDS & POPULARITY REPORT", startDate, endDate);

        // Section 1: Service Ranking
        printSectionDivider("SERVICE POPULARITY RANKING");

        // Query to get services with their bookings in date range
        string rankQuery = "SELECT sv.serviceTypeId, sv.serviceName, sv.basePrice, sv.standardDuration, "
            "IFNULL(booked.booking_count, 0) as bookings, "
            "IFNULL(booked.total_revenue, 0) as revenue "
            "FROM SERVICE_TYPE sv "
            "LEFT JOIN ("
            "    SELECT aps.serviceTypeId, COUNT(*) as booking_count, SUM(svt.basePrice) as total_revenue "
            "    FROM APPOINTMENT_SERVICE aps "
            "    JOIN SERVICE_TYPE svt ON aps.serviceTypeId = svt.serviceTypeId "
            "    JOIN APPOINTMENT a ON aps.appointmentId = a.appointmentId "
            "    JOIN SLOT_TIME st ON a.slotTimeId = st.slotTimeId "
            "    WHERE aps.serviceStatus = 'Completed' "
            "    AND st.slotDate BETWEEN '" + startDate + "' AND '" + endDate + "' "
            "    GROUP BY aps.serviceTypeId"
            ") booked ON sv.serviceTypeId = booked.serviceTypeId "
            "ORDER BY bookings DESC, sv.serviceName";

        if (mysql_query(conn, rankQuery.c_str())) {
            showLoadingComplete();
            showError("Error: " + string(mysql_error(conn)));
            pause();
            return;
        }

        MYSQL_RES* rankResult = mysql_store_result(conn);
        int totalServices = mysql_num_rows(rankResult);
        showLoadingComplete();

        cout << "\033[36m" << left
            << setw(5) << "Rank"
            << setw(30) << "Service Name"
            << setw(12) << "Price"
            << setw(12) << "Duration"
            << setw(10) << "Bookings"
            << setw(15) << "Revenue"
            << "\033[0m" << endl;
        cout << "\033[90m" << repeatString(u8"─", 84) << "\033[0m" << endl;

        MYSQL_ROW row;
        int rank = 1;
        double totalRevenue = 0;
        int totalBookings = 0;
        int topServiceId = 0;
        string topServiceName = "";

        while ((row = mysql_fetch_row(rankResult))) {
            int bookings = row[4] ? atoi(row[4]) : 0;
            double revenue = row[5] ? atof(row[5]) : 0;

            // Medal for top 3
            string medal = "";
            if (rank == 1 && bookings > 0) { medal = "\033[33m[1st]\033[0m "; topServiceId = atoi(row[0]); topServiceName = row[1]; }
            else if (rank == 2 && bookings > 0) medal = "\033[37m[2nd]\033[0m ";
            else if (rank == 3 && bookings > 0) medal = "\033[31m[3rd]\033[0m ";

            cout << left;
            if (!medal.empty()) cout << medal;
            else cout << setw(5) << rank;

            cout << setw(30) << string(row[1]).substr(0, 28)
                << "RM " << setw(9) << row[2]
                << setw(12) << (string(row[3]) + " min");

            if (bookings > 0) {
                cout << setw(10) << bookings
                    << "RM " << fixed << setprecision(2) << revenue;
                // Only add to totals when there are actual bookings
                totalBookings += bookings;
                totalRevenue += revenue;
            } else {
                cout << setw(10) << u8"─" << u8"─";
            }
            cout << endl;
            rank++;
        }
        mysql_free_result(rankResult);

        cout << "\033[90m" << repeatString(u8"─", 84) << "\033[0m" << endl;
        cout << "\033[1;32m" << left << setw(35) << "     TOTAL"
            << setw(12) << "" << setw(12) << ""
            << setw(10) << totalBookings
            << "RM " << fixed << setprecision(2) << totalRevenue
            << "\033[0m" << endl;

        // Section 2: Daily Trend for Top Service
        if (topServiceId > 0) {
            printSectionDivider("DAILY TREND: " + topServiceName);

            string trendQuery = "SELECT st.slotDate, COUNT(*) as daily_bookings "
                "FROM APPOINTMENT_SERVICE aps "
                "JOIN APPOINTMENT a ON aps.appointmentId = a.appointmentId "
                "JOIN SLOT_TIME st ON a.slotTimeId = st.slotTimeId "
                "WHERE aps.serviceTypeId = " + to_string(topServiceId) + " "
                "AND aps.serviceStatus = 'Completed' "
                "AND st.slotDate BETWEEN '" + startDate + "' AND '" + endDate + "' "
                "GROUP BY st.slotDate ORDER BY st.slotDate";

            if (mysql_query(conn, trendQuery.c_str()) == 0) {
                MYSQL_RES* trendResult = mysql_store_result(conn);

                cout << "\033[36m" << left << setw(15) << "Date" << "Bookings" << "\033[0m" << endl;
                cout << "\033[90m" << repeatString(u8"─", 40) << "\033[0m" << endl;

                while ((row = mysql_fetch_row(trendResult))) {
                    int bookings = atoi(row[1]);
                    cout << left << setw(15) << row[0];

                    // Simple bar chart
                    cout << "\033[32m";
                    for (int i = 0; i < bookings; i++) cout << u8"█";
                    cout << "\033[0m " << bookings << endl;
                }
                mysql_free_result(trendResult);
            }
        }

        // Section 3: Service Category Analysis
        printSectionDivider("SERVICE INSIGHTS");
        cout << "\n\033[1;97m  Analysis:\033[0m" << endl;
        cout << "  \033[36m" << u8"├─" << "\033[0m Services Offered:       " << totalServices << endl;
        cout << "  \033[36m" << u8"├─" << "\033[0m Services Booked:        " << totalBookings << endl;
        cout << "  \033[36m" << u8"├─" << "\033[0m Most Popular:           " << topServiceName << endl;
        cout << "  \033[32m" << u8"└─" << "\033[1;32m Total Revenue:          RM " << fixed << setprecision(2) << totalRevenue << "\033[0m" << endl;

        if (totalBookings > 0) {
            cout << "\n  \033[90mAverage Revenue per Booking: RM " << fixed << setprecision(2) << totalRevenue / totalBookings << "\033[0m" << endl;
        }

        printReportFooter(totalBookings);
    }
    catch (OperationCancelledException&) {}
    pause();
}

// ============================================
// 5. CUSTOMER ANALYTICS (DETAILED)
// ============================================
void viewCustomerAnalytics() {
    int choice;
    do {
        clearScreen();
        printSectionTitle("CUSTOMER ANALYTICS & INSIGHTS");

        cout << "\033[1;97mSelect Analytics Type:\033[0m" << endl;
        cout << "\033[36m1.\033[0m VIP Customers (Top Spenders)" << endl;
        cout << "\033[36m2.\033[0m Frequent Visitors (Most Visits)" << endl;
        cout << "\033[36m3.\033[0m Dormant Customers (Inactive > 6 Months)" << endl;
        cout << "\033[36m4.\033[0m New Customer Growth Analysis" << endl;
        cout << "\033[36m5.\033[0m Customer Transaction History" << endl;
        cout << "\n\033[36m0.\033[0m Back to Reports Menu" << endl;

        try {
            choice = getValidInt("\nEnter choice", 0, 5);
            MYSQL_RES* result;
            MYSQL_ROW row;

            switch (choice) {
            case 0: break;
        case 1: // VIP Customers
        {
            clearScreen();
            showLoadingStart("Generating VIP customers report");
            printReportHeader("VIP CUSTOMERS REPORT", "All Time", "Present");

            printSectionDivider("TOP 10 VIP CUSTOMERS BY SPENDING");

            string query = "SELECT c.customerId, c.customerName, c.phoneNumber, c.email, "
                "COUNT(DISTINCT a.appointmentId) as visits, "
                "COUNT(aps.appointmentServiceId) as total_services, "
                "SUM(sv.basePrice) as total_spent "
                "FROM CUSTOMER c "
                "JOIN VEHICLE v ON c.customerId = v.customerId "
                "JOIN APPOINTMENT a ON v.vehicleId = a.vehicleId "
                "JOIN APPOINTMENT_SERVICE aps ON a.appointmentId = aps.appointmentId "
                "JOIN SERVICE_TYPE sv ON aps.serviceTypeId = sv.serviceTypeId "
                "WHERE aps.serviceStatus = 'Completed' "
                "GROUP BY c.customerId "
                "ORDER BY total_spent DESC LIMIT 10";

            if (mysql_query(conn, query.c_str())) { showLoadingComplete(); cout << mysql_error(conn); break; }
            result = mysql_store_result(conn);
            showLoadingComplete();

            cout << "\033[36m" << left
                << setw(5) << "Rank"
                << setw(20) << "Customer"
                << setw(15) << "Phone"
                << setw(8) << "Visits"
                << setw(10) << "Services"
                << setw(15) << "Total Spent"
                << "\033[0m" << endl;
            cout << "\033[90m" << repeatString(u8"─", 73) << "\033[0m" << endl;

            int rank = 1;
            double grandTotal = 0;
            while ((row = mysql_fetch_row(result))) {
                string medal = "";
                if (rank == 1) medal = "\033[33m[VIP]\033[0m ";
                else if (rank == 2) medal = "\033[37m[2nd]\033[0m ";
                else if (rank == 3) medal = "\033[31m[3rd]\033[0m ";

                cout << left;
                if (!medal.empty()) cout << medal;
                else cout << setw(5) << rank;

                cout << setw(20) << string(row[1]).substr(0, 18)
                    << setw(15) << row[2]
                    << setw(8) << row[4]
                    << setw(10) << row[5]
                    << "RM " << row[6] << endl;

                // Show recent services for this VIP
                string recentQuery = "SELECT sv.serviceName, st.slotDate "
                    "FROM APPOINTMENT_SERVICE aps "
                    "JOIN SERVICE_TYPE sv ON aps.serviceTypeId = sv.serviceTypeId "
                    "JOIN APPOINTMENT a ON aps.appointmentId = a.appointmentId "
                    "JOIN SLOT_TIME st ON a.slotTimeId = st.slotTimeId "
                    "JOIN VEHICLE v ON a.vehicleId = v.vehicleId "
                    "WHERE v.customerId = " + string(row[0]) + " "
                    "AND aps.serviceStatus = 'Completed' "
                    "ORDER BY st.slotDate DESC LIMIT 3";

                if (mysql_query(conn, recentQuery.c_str()) == 0) {
                    MYSQL_RES* recentResult = mysql_store_result(conn);
                    MYSQL_ROW recentRow;
                    cout << "\033[90m       " << u8"└─ Recent: ";
                    bool first = true;
                    while ((recentRow = mysql_fetch_row(recentResult))) {
                        if (!first) cout << ", ";
                        cout << recentRow[0] << " (" << recentRow[1] << ")";
                        first = false;
                    }
                    cout << "\033[0m" << endl;
                    mysql_free_result(recentResult);
                }

                grandTotal += atof(row[6]);
                rank++;
            }
            mysql_free_result(result);

            cout << "\033[90m" << repeatString(u8"─", 73) << "\033[0m" << endl;
            cout << "\033[1;32m     TOP 10 VIP TOTAL CONTRIBUTION: RM " << fixed << setprecision(2) << grandTotal << "\033[0m" << endl;

            printReportFooter(rank - 1);
            pause();
            break;
        }

        case 2: // Frequent Visitors
        {
            clearScreen();
            printReportHeader("FREQUENT VISITORS REPORT", "All Time", "Present");

            printSectionDivider("TOP 10 MOST FREQUENT VISITORS");

            string query = "SELECT c.customerId, c.customerName, c.phoneNumber, "
                "COUNT(DISTINCT a.appointmentId) as visits, "
                "MIN(st.slotDate) as first_visit, "
                "MAX(st.slotDate) as last_visit, "
                "SUM(sv.basePrice) as total_spent "
                "FROM CUSTOMER c "
                "JOIN VEHICLE v ON c.customerId = v.customerId "
                "JOIN APPOINTMENT a ON v.vehicleId = a.vehicleId "
                "JOIN APPOINTMENT_SERVICE aps ON a.appointmentId = aps.appointmentId "
                "JOIN SERVICE_TYPE sv ON aps.serviceTypeId = sv.serviceTypeId "
                "JOIN SLOT_TIME st ON a.slotTimeId = st.slotTimeId "
                "WHERE a.status = 'Completed' "
                "GROUP BY c.customerId "
                "ORDER BY visits DESC LIMIT 10";

            if (mysql_query(conn, query.c_str())) { cout << mysql_error(conn); break; }
            result = mysql_store_result(conn);

            cout << "\033[36m" << left
                << setw(20) << "Customer"
                << setw(15) << "Phone"
                << setw(8) << "Visits"
                << setw(12) << "First Visit"
                << setw(12) << "Last Visit"
                << setw(12) << "Spent"
                << "\033[0m" << endl;
            cout << "\033[90m" << repeatString(u8"─", 79) << "\033[0m" << endl;

            while ((row = mysql_fetch_row(result))) {
                cout << left
                    << setw(20) << string(row[1]).substr(0, 18)
                    << setw(15) << row[2]
                    << setw(8) << row[3]
                    << setw(12) << row[4]
                    << setw(12) << row[5]
                    << "RM " << row[6] << endl;
            }
            mysql_free_result(result);

            printReportFooter(10);
            pause();
            break;
        }

        case 3: // Dormant Customers
        {
            clearScreen();
            printReportHeader("DORMANT CUSTOMERS REPORT", "Inactive > 6 Months", "Present");

            printSectionDivider("CUSTOMERS REQUIRING RE-ENGAGEMENT");
            showWarning("RECOMMENDATION: Contact these customers with special offers.\n");

            string query = "SELECT c.customerId, c.customerName, c.phoneNumber, c.email, "
                "MAX(st.slotDate) as last_visit, "
                "DATEDIFF(CURDATE(), MAX(st.slotDate)) as days_inactive, "
                "COUNT(DISTINCT a.appointmentId) as total_visits "
                "FROM CUSTOMER c "
                "JOIN VEHICLE v ON c.customerId = v.customerId "
                "JOIN APPOINTMENT a ON v.vehicleId = a.vehicleId "
                "JOIN SLOT_TIME st ON a.slotTimeId = st.slotTimeId "
                "GROUP BY c.customerId "
                "HAVING last_visit < DATE_SUB(CURDATE(), INTERVAL 6 MONTH) "
                "ORDER BY days_inactive DESC";

            if (mysql_query(conn, query.c_str())) { cout << mysql_error(conn); break; }
            result = mysql_store_result(conn);
            int dormantCount = mysql_num_rows(result);

            if (dormantCount == 0) {
                showSuccess("Excellent! No dormant customers found.");
            } else {
                cout << "\033[36m" << left
                    << setw(20) << "Customer"
                    << setw(15) << "Phone"
                    << setw(25) << "Email"
                    << setw(12) << "Last Visit"
                    << setw(12) << "Days Ago"
                    << "\033[0m" << endl;
                cout << "\033[90m" << repeatString(u8"─", 84) << "\033[0m" << endl;

                while ((row = mysql_fetch_row(result))) {
                    int daysInactive = atoi(row[5]);
                    string urgency = (daysInactive > 365) ? "\033[31m" : "\033[33m";

                    cout << left
                        << setw(20) << string(row[1]).substr(0, 18)
                        << setw(15) << row[2]
                        << setw(25) << (row[3] ? string(row[3]).substr(0, 23) : u8"─")
                        << setw(12) << row[4]
                        << urgency << setw(12) << (string(row[5]) + " days") << "\033[0m" << endl;
                }

                cout << "\n\033[31mTotal Dormant Customers: " << dormantCount << "\033[0m" << endl;
            }
            mysql_free_result(result);

            printReportFooter(dormantCount);
            pause();
            break;
        }

        case 4: // New Customer Growth
        {
            printSubHeader("Define Analysis Period");
            string startD = getSmartDateInput("Enter Start Date");
            string endD = getSmartDateInput("Enter End Date  ");

            clearScreen();
            printReportHeader("NEW CUSTOMER GROWTH ANALYSIS", startD, endD);

            // Monthly breakdown
            printSectionDivider("MONTHLY NEW CUSTOMER REGISTRATIONS");

            string monthQuery = "SELECT DATE_FORMAT(registrationDate, '%Y-%m') as month, "
                "COUNT(*) as new_customers "
                "FROM CUSTOMER "
                "WHERE registrationDate BETWEEN '" + startD + "' AND '" + endD + "' "
                "GROUP BY month ORDER BY month";

            if (mysql_query(conn, monthQuery.c_str()) == 0) {
                MYSQL_RES* monthResult = mysql_store_result(conn);

                cout << "\033[36m" << left << setw(15) << "Month" << "New Customers" << "\033[0m" << endl;
                cout << "\033[90m" << repeatString(u8"─", 40) << "\033[0m" << endl;

                int total = 0;
                while ((row = mysql_fetch_row(monthResult))) {
                    int count = atoi(row[1]);
                    cout << left << setw(15) << row[0];
                    cout << "\033[32m";
                    for (int i = 0; i < count; i++) cout << u8"█";
                    cout << "\033[0m " << count << endl;
                    total += count;
                }
                mysql_free_result(monthResult);

                cout << "\033[90m" << repeatString(u8"─", 40) << "\033[0m" << endl;
                cout << "\033[1;32mTOTAL NEW CUSTOMERS: " << total << "\033[0m" << endl;
            }

            // List new customers
            printSectionDivider("NEW CUSTOMER DETAILS");

            string listQuery = "SELECT customerId, customerName, phoneNumber, email, registrationDate "
                "FROM CUSTOMER "
                "WHERE registrationDate BETWEEN '" + startD + "' AND '" + endD + "' "
                "ORDER BY registrationDate DESC";

            if (mysql_query(conn, listQuery.c_str()) == 0) {
                MYSQL_RES* listResult = mysql_store_result(conn);
                int count = mysql_num_rows(listResult);

                cout << "\033[36m" << left
                    << setw(5) << "ID"
                    << setw(20) << "Name"
                    << setw(15) << "Phone"
                    << setw(25) << "Email"
                    << setw(12) << "Reg. Date"
                    << "\033[0m" << endl;
                cout << "\033[90m" << repeatString(u8"─", 77) << "\033[0m" << endl;

                while ((row = mysql_fetch_row(listResult))) {
                    cout << left
                        << setw(5) << row[0]
                        << setw(20) << string(row[1]).substr(0, 18)
                        << setw(15) << row[2]
                        << setw(25) << (row[3] ? string(row[3]).substr(0, 23) : u8"─")
                        << setw(12) << row[4] << endl;
                }
                mysql_free_result(listResult);

                printReportFooter(count);
            }
            pause();
            break;
        }

        case 5: // Customer Transaction History
        {
            // Step 1: Search for customer
            printSubHeader("Search Customer");
            string term = getValidString("Enter Name, Phone, or Plate");

            string searchQuery = "SELECT DISTINCT c.customerId, c.customerName, c.phoneNumber, "
                "COUNT(DISTINCT v.vehicleId) as vehicles "
                "FROM CUSTOMER c "
                "LEFT JOIN VEHICLE v ON c.customerId = v.customerId "
                "WHERE c.customerName LIKE '%" + term + "%' "
                "OR c.phoneNumber LIKE '%" + term + "%' "
                "OR v.licensePlate LIKE '%" + term + "%' "
                "GROUP BY c.customerId "
                "ORDER BY c.customerName";

            if (mysql_query(conn, searchQuery.c_str())) { cout << mysql_error(conn); break; }
            result = mysql_store_result(conn);

            if (mysql_num_rows(result) == 0) {
                showError("No customers found matching '" + term + "'.");
                mysql_free_result(result);
                pause();
                break;
            }

            cout << "\n\033[1;97m=== Matching Customers ===\033[0m" << endl;
            cout << "\033[36m" << left << setw(5) << "ID" << setw(25) << "Name"
                << setw(15) << "Phone" << setw(10) << "Vehicles" << "\033[0m" << endl;
            cout << "\033[90m" << repeatString(u8"─", 55) << "\033[0m" << endl;

            while ((row = mysql_fetch_row(result))) {
                cout << left << setw(5) << row[0] << setw(25) << row[1]
                    << setw(15) << row[2] << setw(10) << row[3] << endl;
            }
            mysql_free_result(result);

            // Step 2: Select customer
            int custId = getValidInt("\nEnter Customer ID from list", 1, 99999);

            // Get customer info
            string custQuery = "SELECT customerName, phoneNumber, email, registrationDate "
                "FROM CUSTOMER WHERE customerId = " + to_string(custId);

            if (mysql_query(conn, custQuery.c_str())) { cout << mysql_error(conn); break; }
            result = mysql_store_result(conn);

            if (mysql_num_rows(result) == 0) {
                showError("Invalid Customer ID.");
                mysql_free_result(result);
                pause();
                break;
            }

            row = mysql_fetch_row(result);
            string custName = row[0];
            string custPhone = row[1];
            string custEmail = row[2] ? row[2] : "N/A";
            string custRegDate = row[3];
            mysql_free_result(result);

            clearScreen();
            printReportHeader("CUSTOMER TRANSACTION HISTORY", custName, "ID: " + to_string(custId));

            // Customer Info
            printSectionDivider("CUSTOMER INFORMATION");
            cout << "  \033[36mName:\033[0m         " << custName << endl;
            cout << "  \033[36mPhone:\033[0m        " << custPhone << endl;
            cout << "  \033[36mEmail:\033[0m        " << custEmail << endl;
            cout << "  \033[36mMember Since:\033[0m " << custRegDate << endl;

            // Vehicles
            printSectionDivider("REGISTERED VEHICLES");
            string vehQuery = "SELECT vehicleId, licensePlate, brand, model, year, color "
                "FROM VEHICLE WHERE customerId = " + to_string(custId);

            if (mysql_query(conn, vehQuery.c_str()) == 0) {
                MYSQL_RES* vehResult = mysql_store_result(conn);

                cout << "\033[36m" << left
                    << setw(5) << "ID"
                    << setw(12) << "Plate"
                    << setw(15) << "Brand"
                    << setw(15) << "Model"
                    << setw(8) << "Year"
                    << setw(10) << "Color"
                    << "\033[0m" << endl;
                cout << "\033[90m" << repeatString(u8"─", 65) << "\033[0m" << endl;

                while ((row = mysql_fetch_row(vehResult))) {
                    cout << left
                        << setw(5) << row[0]
                        << setw(12) << row[1]
                        << setw(15) << row[2]
                        << setw(15) << row[3]
                        << setw(8) << row[4]
                        << setw(10) << row[5] << endl;
                }
                mysql_free_result(vehResult);
            }

            // Transaction History
            printSectionDivider("SERVICE HISTORY");
            string histQuery = "SELECT a.appointmentId, st.slotDate, v.licensePlate, "
                "GROUP_CONCAT(sv.serviceName SEPARATOR ', ') as services, "
                "SUM(sv.basePrice) as total, a.status "
                "FROM APPOINTMENT a "
                "JOIN VEHICLE v ON a.vehicleId = v.vehicleId "
                "JOIN SLOT_TIME st ON a.slotTimeId = st.slotTimeId "
                "JOIN APPOINTMENT_SERVICE aps ON a.appointmentId = aps.appointmentId "
                "JOIN SERVICE_TYPE sv ON aps.serviceTypeId = sv.serviceTypeId "
                "WHERE v.customerId = " + to_string(custId) + " "
                "GROUP BY a.appointmentId "
                "ORDER BY st.slotDate DESC";

            if (mysql_query(conn, histQuery.c_str()) == 0) {
                MYSQL_RES* histResult = mysql_store_result(conn);
                int histCount = mysql_num_rows(histResult);

                cout << "\033[36m" << left
                    << setw(6) << "ID"
                    << setw(12) << "Date"
                    << setw(12) << "Vehicle"
                    << setw(35) << "Services"
                    << setw(12) << "Amount"
                    << setw(10) << "Status"
                    << "\033[0m" << endl;
                cout << "\033[90m" << repeatString(u8"─", 87) << "\033[0m" << endl;

                double totalSpent = 0;
                while ((row = mysql_fetch_row(histResult))) {
                    string services = row[3];
                    if (services.length() > 33) services = services.substr(0, 30) + "...";

                    string status = row[5];
                    string statusColor = (status == "Completed") ? "\033[32m" :
                                        (status == "Cancelled") ? "\033[31m" : "\033[36m";

                    cout << left
                        << setw(6) << row[0]
                        << setw(12) << row[1]
                        << setw(12) << row[2]
                        << setw(35) << services
                        << "RM " << setw(9) << row[4]
                        << statusColor << status << "\033[0m" << endl;

                    if (status == "Completed") totalSpent += atof(row[4]);
                }
                mysql_free_result(histResult);

                cout << "\033[90m" << repeatString(u8"─", 87) << "\033[0m" << endl;
                cout << "\033[1;32mTOTAL LIFETIME SPENDING: RM " << fixed << setprecision(2) << totalSpent << "\033[0m" << endl;

                printReportFooter(histCount);
            }
            pause();
            break;
        }
            }
        }
        catch (OperationCancelledException&) { choice = -1; }
    } while (choice != 0);
}

// ============================================
// MAIN REPORTS MENU (MANAGER ONLY)
// ============================================
void generateReports() {
    // Access Control Check
    if (!checkReportAccess()) {
        return;
    }

    int choice;
    do {
        clearScreen();
        displayHeader();
        displayBreadcrumb();
        cout << "\n\033[1;97m7.0 ANALYTICS & REPORTS\033[0m \033[33m[MANAGER ONLY]\033[0m\n" << endl;

        cout << "\033[36m1.\033[0m Appointment Schedule Report (Detailed)" << endl;
        cout << "\033[36m2.\033[0m Financial Report (Sales & Revenue)" << endl;
        cout << "\033[36m3.\033[0m Service Trends & Popularity" << endl;
        cout << "\033[36m4.\033[0m Mechanic Performance Report" << endl;
        cout << "\033[36m5.\033[0m Customer Analytics & Insights" << endl;

        cout << "\n\033[36m0.\033[0m Back to Main Menu" << endl;

        try {
            choice = getValidInt("\nEnter choice", 0, 5);
            switch (choice) {
            case 1: setBreadcrumb("Home > Reports > Appointments"); viewAppointmentSchedule(); break;
            case 2: setBreadcrumb("Home > Reports > Financial"); viewFinancialReport(); break;
            case 3: setBreadcrumb("Home > Reports > Service Trends"); viewServiceTrends(); break;
            case 4: setBreadcrumb("Home > Reports > Mechanic Performance"); viewMechanicPerformance(); break;
            case 5: setBreadcrumb("Home > Reports > Customer Analytics"); viewCustomerAnalytics(); break;
            case 0: break;
            }
        }
        catch (OperationCancelledException&) { choice = -1; }
    } while (choice != 0);
}
